apiVersion: v1
kind: ServiceAccount
metadata:
  name: scrape-dispatcher
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: scrape-dispatcher
rules:
  - apiGroups: [batch]
    resources: [jobs]
    verbs: [create, get]
  - apiGroups: [""]
    resources: [configmaps]  # each Job's Supplied Start Requests
    verbs: [create, get]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scrape-dispatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scrape-dispatcher
subjects:
  - kind: ServiceAccount
    name: scrape-dispatcher
