# For a k3d cluster created with the README's runs/ and sites/ mappings.
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: groceries-scraper
    newTag: dev
patches:
  - path: job.yaml
